In [4]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

# __Load Dataset__

In [3]:
df = pd.read_csv(r'C:\Users\ibad\Desktop\Project_Cyber Abuse Detection\data\raw\Cyber Dataset_Orignal.csv',encoding="latin1")

# __Data Understanding__

In [6]:
#Checking first 5 rows

df.head()

                        Comments Classes
0      Tu bohot bekar aadmi hai.       A
1   Aap ki baat bilkul sahi hai.     NaN
2  Chal nikal yahan se bewakoof!       A
3      Yeh movie bohot achi thi.     NaN
4    Tera dimagh kharab hai kya?       A

In [7]:
# Checking last 5 rows

df.tail()

                                         Comments Classes
5159   Tera logic pagalon se bhi zyada ganda hai,       A
5160      Bevakoof insaan ki koi izzat nahi hoti,       A
5161      Teri harkatein dekh kar taras aata hai,       A
5162      Nalayak banda kisi cheez ka layak nahi,       A
5163  Tera munh dekh kar chakkar aane lagte hain,       A

In [8]:
# Checking random 5 rows

df.sample(5)

                                               Comments Classes
3526                        Chxd khud gya bechara india       A
4406  zimbabar ki century ke liye kya kya karna padt...       A
1010      Aur video game ki clip chiye to mujh se le lo     NaN
3735  Phoddi marwany ka itna shouq ta to ab sub k sa...       A
2483  Ony teri bond paaar k hath ch farga chadni ay ...       A

In [9]:
# Checking number of row and columns

df.shape

(5164, 2)

In [10]:
# Columns names

df.columns

Index(['Comments', 'Classes'], dtype='str')

In [11]:
# datatypes of columns

df.dtypes

Comments    str
Classes     str
dtype: object

In [12]:
# Finding NaN

df.isnull().sum()

Comments       0
Classes     2656
dtype: int64

In [13]:
# All unique catogries

df['Classes'].unique()

<StringArray>
['A', nan, 'Na', 'A ', 'NA  ', 'A  ', 'NA ']
Length: 7, dtype: str

In [14]:
# Count all unique catogries

df['Classes'].value_counts()

Classes
A       2485
NA        13
A          5
Na         3
A          1
NA         1
Name: count, dtype: int64

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5164 entries, 0 to 5163
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Comments  5164 non-null   str
 1   Classes   2508 non-null   str
dtypes: str(2)
memory usage: 80.8 KB

# __Data Cleaning__

In [16]:
# Removing the trailing space

df['Classes'] = df['Classes'].str.strip()

In [17]:
# Checking again

print(df['Classes'].unique())
print(df['Classes'].value_counts(dropna=False)) # dropna=False: it also count the NaN values

<StringArray>
['A', nan, 'Na', 'NA']
Length: 4, dtype: str
Classes
NaN    2656
A      2491
NA       14
Na        3
Name: count, dtype: int64

In [18]:
# Na and Na are same(not abusive). Let's clear it make only one value

df['Classes'] = df['Classes'].replace('Na','NA')

In [19]:
# Checking again

print(df['Classes'].unique())
print(df['Classes'].value_counts(dropna=False))

<StringArray>
['A', nan, 'NA']
Length: 3, dtype: str
Classes
NaN    2656
A      2491
NA       17
Name: count, dtype: int64

In [20]:
df["Classes"].isnull().sum()

np.int64(2656)

In [21]:
df.duplicated().sum()

np.int64(211)

In [22]:
# To extract all rows where Classes is NaN:
nan_rows = df[df["Classes"].isna()]

In [23]:
nan_rows.sample(5)

                                 Comments Classes
820             Wo review diya hai 1 star     NaN
2640                                  geo     NaN
4597  1-101 dekhna wala attendance lagaye     NaN
4132                      na kar itna big     NaN
828         Kya baat kahi hai dil jeet li     NaN

In [24]:
# these rows were abusive but marked NaN

df.loc[1290, "Classes"] = "A"
df.loc[4644, "Classes"] = "A"
df.loc[4460, "Classes"] = "A"
df.loc[4912, "Classes"] = "A"
df.loc[1742, "Classes"] = "A"
df.loc[1755, "Classes"] = "A"
df.loc[2183, 'Classes'] = 'A'
df.loc[4023, 'Classes'] = 'NA'
df.loc[4059, 'Classes'] = 'NA'
df.loc[369, 'Classes'] = 'A'
df.loc[4070, 'Classes'] = 'NA'
df.loc[4034, 'Classes'] = 'NA'
df.loc[1629, 'Classes'] = 'A'
df.loc[1595, 'Classes'] = 'A'
df.loc[3168, 'Classes'] = 'A'

In [25]:
# Convert all postive rows to NA

df["Classes"] = df["Classes"].fillna("NA")

In [26]:
# Removing duplicates

df = df.drop_duplicates()

In [27]:
# Checking again

df.sample(5)

                                               Comments Classes
3892  Pakistan ke paas 20 theatres hain, unki film i...      NA
950   Chutiye abhi tak giraftaar pilot ko samne nhi ...       A
4041                        Paisa beizzat mil raha hai        A
4895  6:11 yarr maheen aur meer kai darmeaan khuch h...      NA
2895                                            ok good      NA

In [28]:
# Checking unique catgories

df['Classes'].unique()

<StringArray>
['A', 'NA']
Length: 2, dtype: str

In [29]:
# Counting unique catgores

df['Classes'].value_counts()

Classes
NA    2611
A     2341
Name: count, dtype: int64

In [30]:
# Total number of rows and columns
df.shape

(4952, 2)

# __Preprocessing__

In [31]:
# Create a Copy of the Text

df["clean_comments"] = df['Comments'].copy()
df.sample()

,Comments,Classes,clean_comments
3085,Kutii k bchy post share krny wale,A,Kutii k bchy post share krny wale

### __Lowercasing__

In [32]:
#converting into lowercase

df['clean_comments'] = df['clean_comments'].str.lower()
df.sample()

                        Comments Classes               clean_comments
483  Tera jawab chutiyaapan tha.       A  tera jawab chutiyaapan tha.

### __Removing extra space__

In [33]:
# Check spaces at the beginning or end
(df['clean_comments'] != df['clean_comments'].str.strip()).sum()

np.int64(222)

In [34]:
# Removing the extra space

df['clean_comments'] = df['clean_comments'].str.strip()

In [35]:
# verifying 
(df['clean_comments'] != df['clean_comments'].str.strip()).sum()

np.int64(0)

### __Punctuation__

In [36]:
# cleaning punctuation in the text

import string

df['clean_comments'] = df['clean_comments'].str.translate(str.maketrans("","",string.punctuation))
df.sample()

         Comments Classes clean_comments
3651  Chal dallah       A    chal dallah

### __Remove Extra Whitespace__

In [37]:
#Removing extra whiespace in the text

import re
df['clean_comments'] = df['clean_comments'].str.replace(r'\s+'," ", regex=True).str.strip()
df.sample(5)

,Comments,Classes,clean_comments
316,Coching centre ka hai,NA,coching centre ka hai
1996,Bhosda loda,A,bhosda loda
4932,Ye kia tha aur kuch nahi ab iss dramay mai dra...,NA,ye kia tha aur kuch nahi ab iss dramay mai dra...
2659,video daikh ky chkr a gya,A,video daikh ky chkr a gya
860,"Main India se bol rahi hoon, kaam to Hindustan...",NA,main india se bol rahi hoon kaam to hindustan ...

### __Normalize Repeated Characters__

In [38]:
# Checking Repeation

df[df['clean_comments'].str.contains(r'(.)\1{2,}', regex=True, na=False)][
    ['Comments', 'clean_comments']
].head(5)

C:\Users\ibad\AppData\Local\Temp\ipykernel_14376\3368525758.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df['clean_comments'].str.contains(r'(.)\1{2,}', regex=True, na=False)][

,Comments,clean_comments
110,Are Brooo Pasandida Aurat Milne K Baad Main Ba...,are brooo pasandida aurat milne k baad main ba...
119,sain sanghar me milna heeee apse,sain sanghar me milna heeee apse
359,bhaiii nu labb k dawo koii bhaii tarsyaa pyaa jyy,bhaiii nu labb k dawo koii bhaii tarsyaa pyaa jyy
360,uffffffffffffffffff Yara ya match dobra yad ag...,uffffffffffffffffff yara ya match dobra yad ag...
507,Oooooooh achhhhhha,oooooooh achhhhhha

In [39]:
# Cleaning it

import re

def normalize_repeated_chars(text):
    return re.sub(r'(.)\1{2,}', r'\1\1', text)

df['clean_comments'] = df['clean_comments'].apply(normalize_repeated_chars)
df.loc[360]

Comments          uffffffffffffffffff Yara ya match dobra yad ag...
Classes                                                          NA
clean_comments    uff yara ya match dobra yad ageya ha ab dobra ...
Name: 360, dtype: str

### __Stopwords__

In [40]:
from collections import Counter

word_counts = Counter(
    word
    for comment in df['clean_comments']
    for word in comment.split()
)

word_counts.most_common(30)

[('hai', 1227),
 ('ka', 584),
 ('ki', 563),
 ('ko', 433),
 ('ho', 405),
 ('ke', 393),
 ('to', 367),
 ('nahi', 330),
 ('k', 327),
 ('se', 308),
 ('ye', 292),
 ('bhai', 291),
 ('is', 282),
 ('bhi', 280),
 ('aur', 275),
 ('kar', 268),
 ('hain', 238),
 ('or', 201),
 ('ha', 196),
 ('me', 190),
 ('hi', 188),
 ('mein', 183),
 ('kya', 179),
 ('pakistan', 169),
 ('na', 163),
 ('tu', 161),
 ('he', 155),
 ('tha', 151),
 ('raha', 146),
 ('ab', 143)]

In [41]:
# Removing these stop words
stop_words = [
    'hai', 'ka', 'ki', 'ko', 'ho', 'ke', 'to',
    'se', 'ye', 'is', 'bhi', 'aur', 'kar',
    'hain', 'or', 'ha', 'me', 'mein',
    'tha', 'raha', 'ab'
]

In [42]:
# Creating function for removing stop words
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

In [43]:
df['clean_comments'] = df['clean_comments'].apply(remove_stopwords)

In [44]:
# Checking 
df.sample(5)

,Comments,Classes,clean_comments
5083,"Teri shakal se nafrat hoti hai mujhe,",A,teri shakal nafrat hoti mujhe
5037,Bhosdi mechanic ne machine repair bohot hi kha...,A,bhosdi mechanic ne machine repair bohot hi kha...
4451,Baaki sab ka apne key hote or hain kia katuve ...,A,baaki sab apne key hote kia katuve theek
4454,Sab saaley ka aatankwadi key ke or pilley kia ...,A,sab saaley aatankwadi key pilley kia theek
959,Ht bhosafi ke,A,ht bhosafi

### __empty comments__

In [45]:
# Checking empty comments
df['clean_comments'].eq('').sum()

np.int64(0)

In [46]:
# Let's see what was the orignal comment
df[df['clean_comments'].eq('')][['Comments', 'clean_comments', 'Classes']]

Empty DataFrame
Columns: [Comments, clean_comments, Classes]
Index: []

### __duplicates__

In [47]:
# Checking duplicates again
df['clean_comments'].duplicated().sum()

np.int64(77)

In [48]:
# Let's see the duplicates
duplicate_rows = df[
    df['clean_comments'].duplicated(keep=False)
].sort_values('clean_comments')

duplicate_rows[
    ['Comments', 'clean_comments', 'Classes']
].head(10)

                               Comments             clean_comments Classes
2183                         2No family                 2no family       A
2203                         2no family                 2no family       A
4023  Aman ko serious lena zaroori hai   aman serious lena zaroori      NA
4059      Aman ko serious lena zaroori   aman serious lena zaroori      NA
3978             Arjun Chudega is baar          arjun chudega baar       A
3943              Arjun Chudega is baar         arjun chudega baar       A
1851                          Bakwas ka                     bakwas       A
538                              Bakwas                     bakwas       A
3923                            Bastard                    bastard       A
3914                           Bastard.                    bastard       A

In [49]:
# Checking label complects
label_conflicts = (
    df.groupby('clean_comments')['Classes']
    .nunique()
)

label_conflicts[label_conflicts > 1]

clean_comments
india ap ne bade bahi israel call karty hue    2
Name: Classes, dtype: int64

In [51]:
df[df['clean_comments'] == 'india ap ne bade bahi israel call karty hue'][
    ['Comments', 'clean_comments', 'Classes']
]

,Comments,clean_comments,Classes
1198,India ap ne bade bahi Israel ko call karty hue,india ap ne bade bahi israel call karty hue,NA
1214,India ap ne bade bahi Israel ko call karty hue,india ap ne bade bahi israel call karty hue,A

In [52]:
df.loc[1214, 'Classes'] = 'NA'

In [53]:
# Removing the one set of duplicates
df = df.drop_duplicates(
    subset='clean_comments',
    keep='first'
).copy()

# __Verification__

In [54]:
# Checking null
df.isnull().sum()

Comments          0
Classes           0
clean_comments    0
dtype: int64

In [55]:
# Checking empty comment
df['clean_comments'].eq('').sum()

np.int64(0)

In [56]:
# Checking label distribution
df['Classes'].unique()

<StringArray>
['A', 'NA']
Length: 2, dtype: str

In [57]:
# Checking duplicates again
df['clean_comments'].duplicated().sum()

np.int64(0)

In [58]:
# Checking datashape
df.shape

(4875, 3)

# __Inspect Final Data__

In [59]:
df[['Comments', 'clean_comments', 'Classes']].sample(10, random_state=42)

,Comments,clean_comments,Classes
1640,Yeh kiya bawaserr phila rhay ho,yeh kiya bawaserr phila rhay,A
4454,Sab saaley ka aatankwadi key ke or pilley kia ...,sab saaley aatankwadi key pilley kia theek,A
3033,got famous without doing any chichorapan...,got famous without doing any chichorapan,NA
4897,Floop tareen drama,floop tareen drama,NA
3970,Unko paisa hi beizzat ho k mil raha hai,unko paisa hi beizzat k mil,A
4155,Do do haath mere rehndeo paisay kehti daayi pe...,do do haath mere rehndeo paisay kehti daayi pe...,NA
506,Laant ho ap pe,laant ap pe,A
2855,chilling video,chilling video,NA
3390,Pei bar tiktokers ne acha kam kra ha me tu kah...,pei bar tiktokers ne acha kam kra tu kahoga ek...,A
2513,chlo koi gal nai,chlo koi gal nai,NA