In [4]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

# __Load Dataset__

In [3]:
df = pd.read_csv(r'C:\Users\ibad\Desktop\Project_Cyber Abuse Detection\data\raw\Cyber Dataset_Orignal.csv',encoding="latin1")

# __Data Understanding__

In [6]:
#Checking first 5 rows

df.head()

                        Comments Classes
0      Tu bohot bekar aadmi hai.       A
1   Aap ki baat bilkul sahi hai.     NaN
2  Chal nikal yahan se bewakoof!       A
3      Yeh movie bohot achi thi.     NaN
4    Tera dimagh kharab hai kya?       A

In [7]:
# Checking last 5 rows

df.tail()

                                         Comments Classes
5159   Tera logic pagalon se bhi zyada ganda hai,       A
5160      Bevakoof insaan ki koi izzat nahi hoti,       A
5161      Teri harkatein dekh kar taras aata hai,       A
5162      Nalayak banda kisi cheez ka layak nahi,       A
5163  Tera munh dekh kar chakkar aane lagte hain,       A

In [8]:
# Checking random 5 rows

df.sample(5)

                                               Comments Classes
3526                        Chxd khud gya bechara india       A
4406  zimbabar ki century ke liye kya kya karna padt...       A
1010      Aur video game ki clip chiye to mujh se le lo     NaN
3735  Phoddi marwany ka itna shouq ta to ab sub k sa...       A
2483  Ony teri bond paaar k hath ch farga chadni ay ...       A

In [9]:
# Checking number of row and columns

df.shape

(5164, 2)

In [10]:
# Columns names

df.columns

Index(['Comments', 'Classes'], dtype='str')

In [11]:
# datatypes of columns

df.dtypes

Comments    str
Classes     str
dtype: object

In [12]:
# Finding NaN

df.isnull().sum()

Comments       0
Classes     2656
dtype: int64

In [13]:
# All unique catogries

df['Classes'].unique()

<StringArray>
['A', nan, 'Na', 'A ', 'NA  ', 'A  ', 'NA ']
Length: 7, dtype: str

In [14]:
# Count all unique catogries

df['Classes'].value_counts()

Classes
A       2485
NA        13
A          5
Na         3
A          1
NA         1
Name: count, dtype: int64

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5164 entries, 0 to 5163
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Comments  5164 non-null   str
 1   Classes   2508 non-null   str
dtypes: str(2)
memory usage: 80.8 KB