In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

# __Load Dataset__

In [2]:
df = pd.read_csv(r'C:\Users\ibad\Desktop\Project_Cyber Abuse Detection\data\raw\Cyber Dataset_Orignal.csv',encoding="latin1")

# __Data Understanding__

In [3]:
#Checking first 5 rows

df.head()

                        Comments Classes
0      Tu bohot bekar aadmi hai.       A
1   Aap ki baat bilkul sahi hai.     NaN
2  Chal nikal yahan se bewakoof!       A
3      Yeh movie bohot achi thi.     NaN
4    Tera dimagh kharab hai kya?       A

In [4]:
# Checking last 5 rows

df.tail()

                                         Comments Classes
5159   Tera logic pagalon se bhi zyada ganda hai,       A
5160      Bevakoof insaan ki koi izzat nahi hoti,       A
5161      Teri harkatein dekh kar taras aata hai,       A
5162      Nalayak banda kisi cheez ka layak nahi,       A
5163  Tera munh dekh kar chakkar aane lagte hain,       A

In [5]:
# Checking random 5 rows

df.sample(5)

                                               Comments Classes
1135                     Tumhari soch bohot ghatiya hai       A
4691          Nisa ki maa sab se achi hai is drama mein     NaN
2787                                   kitna sukoon hai     NaN
3231        Bhai ap log sai ho hm sy to Saal bd NH hoti     NaN
3457  Isha Isha Vulgar language use krty hue career ...       A

In [6]:
# Checking number of row and columns

df.shape

(5164, 2)

In [7]:
# Columns names

df.columns

Index(['Comments', 'Classes'], dtype='str')

In [8]:
# datatypes of columns

df.dtypes

Comments    str
Classes     str
dtype: object

In [9]:
# Finding NaN

df.isnull().sum()

Comments       0
Classes     2656
dtype: int64

In [10]:
# All unique catogries

df['Classes'].unique()

<StringArray>
['A', nan, 'Na', 'A ', 'NA  ', 'A  ', 'NA ']
Length: 7, dtype: str

In [11]:
# Count all unique catogries

df['Classes'].value_counts()

Classes
A       2485
NA        13
A          5
Na         3
A          1
NA         1
Name: count, dtype: int64

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5164 entries, 0 to 5163
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Comments  5164 non-null   str
 1   Classes   2508 non-null   str
dtypes: str(2)
memory usage: 80.8 KB

# __Data Cleaning__

In [13]:
# Removing the trailing space

df['Classes'] = df['Classes'].str.strip()

In [14]:
# Checking again

print(df['Classes'].unique())
print(df['Classes'].value_counts(dropna=False)) # dropna=False: it also count the NaN values

<StringArray>
['A', nan, 'Na', 'NA']
Length: 4, dtype: str
Classes
NaN    2656
A      2491
NA       14
Na        3
Name: count, dtype: int64

In [15]:
# Na and Na are same(not abusive). Let's clear it make only one value

df['Classes'] = df['Classes'].replace('Na','NA')

In [16]:
# Checking again

print(df['Classes'].unique())
print(df['Classes'].value_counts(dropna=False))

<StringArray>
['A', nan, 'NA']
Length: 3, dtype: str
Classes
NaN    2656
A      2491
NA       17
Name: count, dtype: int64

In [17]:
df["Classes"].isnull().sum()

np.int64(2656)

In [18]:
df.duplicated().sum()

np.int64(211)

In [19]:
# To extract all rows where Classes is NaN:
nan_rows = df[df["Classes"].isna()]

In [20]:
nan_rows.sample(5)

                                               Comments Classes
2141  Bathroom kab gaye aur kitni der ke liye ye nah...     NaN
4733  Kya paka rahe hai ye log kasam se ek manto dek...     NaN
4756  Boht he extra time tha mere pas soch khichrri ...     NaN
4618  Finally ending, be good for every human being,...     NaN
2166                                          Mashallah     NaN

In [21]:
# these rows were abusive but marked NaN

df.loc[1290, "Classes"] = "A"
df.loc[4644, "Classes"] = "A"
df.loc[4460, "Classes"] = "A"
df.loc[4912, "Classes"] = "A"
df.loc[1742, "Classes"] = "A"
df.loc[1755, "Classes"] = "A"
df.loc[2183, 'Classes'] = 'A'
df.loc[4023, 'Classes'] = 'NA'
df.loc[4059, 'Classes'] = 'NA'
df.loc[369, 'Classes'] = 'A'
df.loc[4070, 'Classes'] = 'NA'
df.loc[4034, 'Classes'] = 'NA'
df.loc[1629, 'Classes'] = 'A'
df.loc[1595, 'Classes'] = 'A'
df.loc[3168, 'Classes'] = 'A'

In [22]:
# Convert all postive rows to NA

df["Classes"] = df["Classes"].fillna("NA")

In [23]:
# Removing duplicates

df = df.drop_duplicates()

In [24]:
# Checking again

df.sample(5)

                                               Comments Classes
1905                                         Madar vlog       A
3891  Eh oh bhaichare waale logan de muh te thappad ...      NA
1583  Ya sub maa siro ka bolny ka tareeqa ek jesa hi...      NA
4040                   Na ghairat aur sharam haya nahi        A
2426  Bhai apni zindagi ka kuch karo bs vlog bna k k...      NA

In [25]:
# Checking unique catgories

df['Classes'].unique()

<StringArray>
['A', 'NA']
Length: 2, dtype: str

In [26]:
# Counting unique catgores

df['Classes'].value_counts()

Classes
NA    2611
A     2341
Name: count, dtype: int64

In [27]:
# Total number of rows and columns
df.shape

(4952, 2)

# __Preprocessing__

In [28]:
# Create a Copy of the Text

df["clean_comments"] = df['Comments'].copy()
df.sample()

,Comments,Classes,clean_comments
3063,Agar Sach he tho acha howa pakistan me reh kar...,A,Agar Sach he tho acha howa pakistan me reh kar...

### __Lowercasing__

In [29]:
#converting into lowercase

df['clean_comments'] = df['clean_comments'].str.lower()
df.sample()

                          Comments Classes                  clean_comments
37  Yeh design bohot creative hai.      NA  yeh design bohot creative hai.

### __Removing extra space__

In [30]:
# Check spaces at the beginning or end
(df['clean_comments'] != df['clean_comments'].str.strip()).sum()

np.int64(222)

In [31]:
# Removing the extra space

df['clean_comments'] = df['clean_comments'].str.strip()

In [32]:
# verifying 
(df['clean_comments'] != df['clean_comments'].str.strip()).sum()

np.int64(0)

### __Punctuation__

In [33]:
# cleaning punctuation in the text

import string

df['clean_comments'] = df['clean_comments'].str.translate(str.maketrans("","",string.punctuation))
df.sample()

                             Comments Classes                   clean_comments
3022  Aapki bardasht qabil e deed thi      NA  aapki bardasht qabil e deed thi

### __Remove Extra Whitespace__

In [34]:
#Removing extra whiespace in the text

import re
df['clean_comments'] = df['clean_comments'].str.replace(r'\s+'," ", regex=True).str.strip()
df.sample(5)

,Comments,Classes,clean_comments
5058,"Nalayak insaan society ka bojh ban gaya hai,",A,nalayak insaan society ka bojh ban gaya hai
4398,Ghanta banenge World Leader,A,ghanta banenge world leader
3928,Chal sala gandu kutta poorstani masalli ??,A,chal sala gandu kutta poorstani masalli
2562,Lekin inu NE boht acha present kiya hai,NA,lekin inu ne boht acha present kiya hai
3533,"Tatti kar le MC, Qabz me esi awazen niklti",A,tatti kar le mc qabz me esi awazen niklti

### __Normalize Repeated Characters__

In [35]:
# Checking Repeation

df[df['clean_comments'].str.contains(r'(.)\1{2,}', regex=True, na=False)][
    ['Comments', 'clean_comments']
].head(5)

C:\Users\ibad\AppData\Local\Temp\ipykernel_16652\3368525758.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df['clean_comments'].str.contains(r'(.)\1{2,}', regex=True, na=False)][

,Comments,clean_comments
110,Are Brooo Pasandida Aurat Milne K Baad Main Ba...,are brooo pasandida aurat milne k baad main ba...
119,sain sanghar me milna heeee apse,sain sanghar me milna heeee apse
359,bhaiii nu labb k dawo koii bhaii tarsyaa pyaa jyy,bhaiii nu labb k dawo koii bhaii tarsyaa pyaa jyy
360,uffffffffffffffffff Yara ya match dobra yad ag...,uffffffffffffffffff yara ya match dobra yad ag...
507,Oooooooh achhhhhha,oooooooh achhhhhha

In [36]:
# Cleaning it

import re

def normalize_repeated_chars(text):
    return re.sub(r'(.)\1{2,}', r'\1\1', text)

df['clean_comments'] = df['clean_comments'].apply(normalize_repeated_chars)
df.loc[360]

Comments          uffffffffffffffffff Yara ya match dobra yad ag...
Classes                                                          NA
clean_comments    uff yara ya match dobra yad ageya ha ab dobra ...
Name: 360, dtype: str

### __Stopwords__

In [37]:
from collections import Counter

word_counts = Counter(
    word
    for comment in df['clean_comments']
    for word in comment.split()
)

word_counts.most_common(30)

[('hai', 1227),
 ('ka', 584),
 ('ki', 563),
 ('ko', 433),
 ('ho', 405),
 ('ke', 393),
 ('to', 367),
 ('nahi', 330),
 ('k', 327),
 ('se', 308),
 ('ye', 292),
 ('bhai', 291),
 ('is', 282),
 ('bhi', 280),
 ('aur', 275),
 ('kar', 268),
 ('hain', 238),
 ('or', 201),
 ('ha', 196),
 ('me', 190),
 ('hi', 188),
 ('mein', 183),
 ('kya', 179),
 ('pakistan', 169),
 ('na', 163),
 ('tu', 161),
 ('he', 155),
 ('tha', 151),
 ('raha', 146),
 ('ab', 143)]

In [38]:
# Removing these stop words
stop_words = [
    'hai', 'ka', 'ki', 'ko', 'ho', 'ke', 'to',
    'se', 'ye', 'is', 'bhi', 'aur', 'kar',
    'hain', 'or', 'ha', 'me', 'mein',
    'tha', 'raha', 'ab'
]

In [39]:
# Creating function for removing stop words
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

In [40]:
df['clean_comments'] = df['clean_comments'].apply(remove_stopwords)

In [41]:
# Checking 
df.sample(5)

,Comments,Classes,clean_comments
4230,Sab ke sab atankwaadi ke pille hain.,A,sab sab atankwaadi pille
1127,Tere jaise chhoti soch ke log har jagah milte ...,A,tere jaise chhoti soch log har jagah milte
1823,Madar content,A,madar content
577,"Yehi wo Khan hai jiska naam Imran Khan hai, Pa...",NA,yehi wo khan jiska naam imran khan pakistan sh...
1753,Whole family is becoming blogger pretty sure n...,NA,whole family becoming blogger pretty sure next...

### __empty comments__

In [42]:
# Checking empty comments
df['clean_comments'].eq('').sum()

np.int64(0)

In [43]:
# Let's see what was the orignal comment
df[df['clean_comments'].eq('')][['Comments', 'clean_comments', 'Classes']]

Empty DataFrame
Columns: [Comments, clean_comments, Classes]
Index: []

### __duplicates__

In [44]:
# Checking duplicates again
df['clean_comments'].duplicated().sum()

np.int64(77)

In [45]:
# Let's see the duplicates
duplicate_rows = df[
    df['clean_comments'].duplicated(keep=False)
].sort_values('clean_comments')

duplicate_rows[
    ['Comments', 'clean_comments', 'Classes']
].head(10)

                               Comments             clean_comments Classes
2183                         2No family                 2no family       A
2203                         2no family                 2no family       A
4023  Aman ko serious lena zaroori hai   aman serious lena zaroori      NA
4059      Aman ko serious lena zaroori   aman serious lena zaroori      NA
3978             Arjun Chudega is baar          arjun chudega baar       A
3943              Arjun Chudega is baar         arjun chudega baar       A
1851                          Bakwas ka                     bakwas       A
538                              Bakwas                     bakwas       A
3923                            Bastard                    bastard       A
3914                           Bastard.                    bastard       A

In [46]:
# Checking label complects
label_conflicts = (
    df.groupby('clean_comments')['Classes']
    .nunique()
)

label_conflicts[label_conflicts > 1]

clean_comments
india ap ne bade bahi israel call karty hue    2
Name: Classes, dtype: int64

In [47]:
df[df['clean_comments'] == 'india ap ne bade bahi israel call karty hue'][
    ['Comments', 'clean_comments', 'Classes']
]

,Comments,clean_comments,Classes
1198,India ap ne bade bahi Israel ko call karty hue,india ap ne bade bahi israel call karty hue,NA
1214,India ap ne bade bahi Israel ko call karty hue,india ap ne bade bahi israel call karty hue,A

In [48]:
df.loc[1214, 'Classes'] = 'NA'

In [49]:
# Removing the one set of duplicates
df = df.drop_duplicates(
    subset='clean_comments',
    keep='first'
).copy()

# __Verification__

In [50]:
# Checking null
df.isnull().sum()

Comments          0
Classes           0
clean_comments    0
dtype: int64

In [51]:
# Checking empty comment
df['clean_comments'].eq('').sum()

np.int64(0)

In [52]:
# Checking label distribution
df['Classes'].unique()

<StringArray>
['A', 'NA']
Length: 2, dtype: str

In [53]:
# Checking duplicates again
df['clean_comments'].duplicated().sum()

np.int64(0)

In [54]:
# Checking datashape
df.shape

(4875, 3)

# __Inspect Final Data__

In [55]:
df[['Comments', 'clean_comments', 'Classes']].sample(10, random_state=42)

,Comments,clean_comments,Classes
1640,Yeh kiya bawaserr phila rhay ho,yeh kiya bawaserr phila rhay,A
4454,Sab saaley ka aatankwadi key ke or pilley kia ...,sab saaley aatankwadi key pilley kia theek,A
3033,got famous without doing any chichorapan...,got famous without doing any chichorapan,NA
4897,Floop tareen drama,floop tareen drama,NA
3970,Unko paisa hi beizzat ho k mil raha hai,unko paisa hi beizzat k mil,A
4155,Do do haath mere rehndeo paisay kehti daayi pe...,do do haath mere rehndeo paisay kehti daayi pe...,NA
506,Laant ho ap pe,laant ap pe,A
2855,chilling video,chilling video,NA
3390,Pei bar tiktokers ne acha kam kra ha me tu kah...,pei bar tiktokers ne acha kam kra tu kahoga ek...,A
2513,chlo koi gal nai,chlo koi gal nai,NA

# __Spliting Data__

### __Spliting Data into features and targets__

In [56]:
# Features
X = df['clean_comments']

# Target
y = df['Classes']

### __Spliting into training and testing data__

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_text, y_train, y_test = train_test_split(
    X,
    y,
    random_state=42,
    shuffle=True,
    stratify=y
)

In [58]:
# Verifying

print(f"X Train: {X_train.shape}")
print(f"X_text: {X_text.shape}")
print(f"Y_train: {y_train.shape}")
print(f"y_test: {y_test.shape}")

X Train: (3656,)
X_text: (1219,)
Y_train: (3656,)
y_test: (1219,)

In [59]:
# check the class distribution.
print("Training Set")
print(y_train.value_counts())

print("\nTesting Set")
print(y_test.value_counts())

Training Set
Classes
NA    1943
A     1713
Name: count, dtype: int64

Testing Set
Classes
NA    648
A     571
Name: count, dtype: int64